### ISSUE TITLE
Задания 1-2

### ISSUE THREAD

**Issue by TrubnikovGI** [TrubnikovGI/Unity2020-Trubnikov#1]
Сергей Иванович, мой компьютер отказывается загружать на гитхаб весь проект юнити, поэтому я выложил для каждого из проектов только папку с билдом и папку со скриптами. Если ещё что-то будет нужно, добавлю

**Comment by justjune** [comment]
Гоша, вы его из командной строки выгружаете?

**Comment by TrubnikovGI** [comment]
теперь проекты выложены целиком (пересоздал гит в папке с проектами и всё заработало)
