### ISSUE TITLE
задания 5-6

### ISSUE THREAD

**Issue by TrubnikovGI** [TrubnikovGI/Unity2020-Trubnikov#3]
Здравствуйте, я добавил два проекта (мат маятник с использованием HingeJoint и точку в поле силы тяжести с использованием средств физики в Unity). Я забылся и когда у себя на компьютере добавлял в гит новые проекты добавил ещё данные об удалении прошлых, уже проверенных проектов, и теперь с репозитория пропали проекты RollaBall и Oscillator1. Я не знаю можно ли в такой ситуации откатить гит, но эти проекты вы уже проверили у меня, так что наверное ничего страшного, в будущем буду осторожнее.

**Comment by justjune** [comment]
См. Успеваемость.
Замечания:

1. В начальный момент времени к телу добавляется скорость, но забыли добавить силу.
2. ForceMode.Force добавляет силу, которая действует непрерывно с момента добавления --- это означает, что у вас на каждом обновлении добавляется еще одна сила, а не то, что сила менятеся.
3. Те проекты, которые уже зачтены можно не восстанавливать. Если вам этого хочтеся, то любой файл или каталог из предыдущего коммита можно восстановить: https://webhamster.ru/mytetrashare/index/mtb0/1405456063y5nfqau8pl?
